# This is a basic workflow to help you get started with Actions

name: GHCR Publish [manual]

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@1.0.2
        name: Build and Publish latest service image
        with:
          # Read note below to see how to generate the PAT
          personal-access-token: ${{ secrets.GHCR_PAT }}
          docker-image-name: LAPS-WebUI
          docker-image-tag: latest
          dockerfile-path: src/Dockerfile
          build-context: ./src
